name: Automerger

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify pull request mergeability
        id: check_mergeable
        run: |
          curl -s -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge" \
          | jq -r '.mergeable' > mergeable.txt

      - name: Read mergeable status
        id: read_mergeable
        run: |
          mergeable_status=$(cat mergeable.txt)
          echo "::set-output name=mergeable_status::$mergeable_status"

      - name: Merge pull request
        if: steps.read_mergeable.outputs.mergeable_status == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --no-ff --no-edit ${{ github.event.pull_request.head.ref }}
          git push origin ${{ github.event.pull_request.base.ref }}
