name: Automerger

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Verify pull request mergeability
        id: check_mergeable
        run: |
          if [[ $(curl -s -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge" \
          | jq -r '.mergeable') == "true" ]]; then
            echo "::set-output name=mergeable::true"
          else
            echo "::set-output name=mergeable::false"
          fi

      - name: Merge pull request
        if: steps.check_mergeable.outputs.mergeable == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --no-ff --no-edit ${{ github.event.pull_request.head.ref }}
          git push origin ${{ github.event.pull_request.base.ref }}
